FROM nvidia/cuda:12.4.0-devel-ubuntu22.04

WORKDIR /workspace

RUN apt-get update && apt-get install -y \
    build-essential git cmake wget curl \
    libssl-dev libgmp-dev libmpfr-dev libeigen3-dev \
    python3-pip pkg-config && \
    apt-get clean && rm -rf /var/lib/apt/lists/*


COPY emp-tool /workspace/emp-tool
RUN mkdir -p /workspace/emp-tool/build && cd /workspace/emp-tool/build && \
    cmake .. && make -j$(nproc) && make install

COPY emp-ot /workspace/emp-ot
RUN mkdir -p /workspace/emp-ot/build && cd /workspace/emp-ot/build && \
    cmake .. && make -j$(nproc) && make install

ENV CMAKE_PREFIX_PATH="/usr/local/lib/cmake/emp-tool:/usr/local/lib/cmake/emp-ot:$CMAKE_PREFIX_PATH"

COPY . /workspace

RUN rm -rf build && mkdir -p build && cd build && cmake .. && make -j$(nproc)

CMD ["/bin/bash"]
